workflows:
  build-web:
    name: Build Flutter Web
    max_build_duration: 20
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - name: Clean old builds
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build web release
        script: flutter build web --release
    artifacts:
      - build/web
